---
version: '3.3'

services:
  bookstack-db:
    image: mariadb:10.4
    container_name: bookstack-db
    restart: always
    volumes:
      - /var/docker/bookstack/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= # Setze hier ein starkes Passwort
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD= # Ein anderes Passwort
      - MYSQL_INITDB_SKIP_TZINFO=1

  bookstack-app:
    image: linuxserver/bookstack:latest
    container_name: bookstack-app
    restart: always
    volumes:
      - /var/docker/bookstack/app:/config
    environment:
      - DB_HOST=bookstack-db:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD= # Hier das Passwort von MYSQL_PASSWORD aus dem Datenbankcontainer setzen
     # - APP_URL=https://bookstack.example.com // Anpassen, wenn Traefik verwendet wird!
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.bookstack-https.redirectscheme.scheme=https"
      - "traefik.http.routers.bookstack-http.entrypoints=web"
      - "traefik.http.routers.bookstack-http.rule=Host(`bookstack.example.com`)" #Domain anpassen
      - "traefik.http.routers.bookstack-http.middlewares=bookstack-https@docker"
      - "traefik.http.routers.bookstack.entrypoints=web-secure"
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.example.com`)" #Domain anpassen
      - "traefik.http.routers.bookstack.tls=true"
      - "traefik.http.routers.bookstack.tls.certresolver=default"
      - "traefik.http.routers.bookstack.middlewares=secHeaders@file"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
    depends_on:
      - bookstack-db
    networks:
      - traefik_proxy
      - default
      
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
